### PR TITLE
fix: Multiple Bugs Identified in the Codebase

### PR DESCRIPTION
**Pull request by FatefulNur**
### Fixes:
**Migration:**
Added a new migration to:
- Modify the posted_at column to allow NULL values.
- Rename the expaire_at column to expired_at to fix a typo and ensure consistency.

**Nullable posted_at Column Issue:**
Resolved errors caused by NULL values in the posted_at column, such as:
- Call to a member function diffForHumans() on null
- Call to a member function isoFormat() on null
- Call to a member function job_title on null
- Reviewed and updated views and logic across the application to properly handle scenarios where **posted_at** or **`job_title` of user experience** may be NULL.

> In production need to add `php artisan migrate` command to affect new changes

### CODE REVIEW

**Comment by theihasan** [comment]
Is there any uses of expired_at in the codebase? Have explored it?

**Comment by FatefulNur** [comment]
Yes i have fixed all the use cases

**Comment by FatefulNur** [comment]
A little fix added of migration check b869def473f4d3de8eeda592757f3882e1b649c3

**Comment by FatefulNur** [comment]
Should close #10 @theihasan

**Pull request merged**
